version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - sls deploy -v